# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vadu-simpify-app"
client_id = "b782e866f44fe9ffb2c6dfd37b787d76"
application_url = "https://quarter-sets-expenditures-stroke.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://quarter-sets-expenditures-stroke.trycloudflare.com/auth/callback",
  "https://quarter-sets-expenditures-stroke.trycloudflare.com/auth/shopify/callback",
  "https://quarter-sets-expenditures-stroke.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vadu-test-store.myshopify.com"
